frase = str(input('Digite uma frase: ')).strip()
u = frase.upper()
print('A letra A aparece {} vezes na frase'.format(u.count('A')))
print('A primeira letra A apareceu na posiçao {}'.format(u.find('A')+1))
print('A ultima letra A aparece na posiçao {}'.format(u.rfind('A')+1))
