n = str(input('Digite seu nome completo: ')).strip().split()
#d = n.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(n[0]))
print('Seu ultimo nome é {}'.format(n[-1]))
